/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package coba;

/**
 *
 * @author PC RPL - R1
 */
public class Percobaan10 extends javax.swing.JFrame {

    /**
     * Creates new form bismillah10
     */
    public Percobaan10() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eHasil = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        eData1 = new javax.swing.JTextField();
        eData2 = new javax.swing.JTextField();
        eData3 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menProses = new javax.swing.JMenu();
        meltBersih = new javax.swing.JMenu();
        menHitung = new javax.swing.JMenu();
        meltLuasPersegiPanjang = new javax.swing.JMenuItem();
        meltKelilingPersegiPanjang = new javax.swing.JMenuItem();
        meltLuasSegitiga = new javax.swing.JMenuItem();
        meltKelilingSegitiga = new javax.swing.JMenuItem();
        meltLuasLingkaran = new javax.swing.JMenuItem();
        meltKelilingLingkaran = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Data1");

        jLabel2.setText("Data2");

        jLabel3.setText("Data3");

        jLabel4.setText("Hasil");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        menProses.setText("Proses");

        meltBersih.setText("Bersih");
        menProses.add(meltBersih);

        menHitung.setText("Hitung");

        meltLuasPersegiPanjang.setText("Luas Persegi Panjang");
        meltLuasPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltLuasPersegiPanjangActionPerformed(evt);
            }
        });
        menHitung.add(meltLuasPersegiPanjang);

        meltKelilingPersegiPanjang.setText("Keliling PersegiPanjang");
        meltKelilingPersegiPanjang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltKelilingPersegiPanjangActionPerformed(evt);
            }
        });
        menHitung.add(meltKelilingPersegiPanjang);

        meltLuasSegitiga.setText("Luas Segitiga");
        meltLuasSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltLuasSegitigaActionPerformed(evt);
            }
        });
        menHitung.add(meltLuasSegitiga);

        meltKelilingSegitiga.setText("Keliling Segitiga");
        meltKelilingSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltKelilingSegitigaActionPerformed(evt);
            }
        });
        menHitung.add(meltKelilingSegitiga);

        meltLuasLingkaran.setText("Luas Lingkaran");
        meltLuasLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltLuasLingkaranActionPerformed(evt);
            }
        });
        menHitung.add(meltLuasLingkaran);

        meltKelilingLingkaran.setText("Keliling Lingkaran");
        meltKelilingLingkaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meltKelilingLingkaranActionPerformed(evt);
            }
        });
        menHitung.add(meltKelilingLingkaran);

        menProses.add(menHitung);

        jMenuBar1.add(menProses);

        jMenu3.setText("Bantuan");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(eData1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(eData2)
                    .addComponent(eData3)
                    .addComponent(eHasil))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eData1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(eData2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(eData3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void meltLuasPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltLuasPersegiPanjangActionPerformed
        // TODO add your handling code here:
        int panjang = Integer.parseInt(eData1.getText());
        int lebar = Integer.parseInt(eData2.getText());
        int luas = panjang * lebar;
        eHasil.setText(String.valueOf(luas));

    }//GEN-LAST:event_meltLuasPersegiPanjangActionPerformed

    private void meltKelilingPersegiPanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltKelilingPersegiPanjangActionPerformed
        // TODO add your handling code here:
        int panjang = Integer.parseInt(eData1.getText());
        int lebar = Integer.parseInt(eData2.getText());
        int luas = panjang * lebar;
        eHasil.setText(String.valueOf(luas));
    }//GEN-LAST:event_meltKelilingPersegiPanjangActionPerformed

    private void meltLuasSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltLuasSegitigaActionPerformed
        // TODO add your handling code here:
        int alas = Integer.parseInt(eData1.getText());
        int tinggi = Integer.parseInt(eData2.getText());
        int luas = (alas * tinggi) / 2;
        eHasil.setText(String.valueOf(luas));
    }//GEN-LAST:event_meltLuasSegitigaActionPerformed

    private void meltKelilingSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltKelilingSegitigaActionPerformed
        // TODO add your handling code here:
        int Data1 = Integer.parseInt(eData1.getText());
        int Data2 = Integer.parseInt(eData2.getText());
        int Data3 = Integer.parseInt(eData3.getText());
        int keliling = Data1 + Data2 + Data3;
        eHasil.setText(String.valueOf(keliling));
    }//GEN-LAST:event_meltKelilingSegitigaActionPerformed

    private void meltLuasLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltLuasLingkaranActionPerformed
        // TODO add your handling code here:
        double radius = Double.parseDouble(eData1.getText());
        double luas = Math.PI * radius * radius;
        eHasil.setText(String.valueOf(luas));
    }//GEN-LAST:event_meltLuasLingkaranActionPerformed

    private void meltKelilingLingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meltKelilingLingkaranActionPerformed
        // TODO add your handling code here:
        double radius = Double.parseDouble(eData1.getText());
        double keliling = 2 * Math.PI * radius;
        eHasil.setText(String.valueOf(keliling));
    }//GEN-LAST:event_meltKelilingLingkaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Percobaan10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Percobaan10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Percobaan10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Percobaan10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Percobaan10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField eData1;
    private javax.swing.JTextField eData2;
    private javax.swing.JTextField eData3;
    private javax.swing.JTextField eHasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu meltBersih;
    private javax.swing.JMenuItem meltKelilingLingkaran;
    private javax.swing.JMenuItem meltKelilingPersegiPanjang;
    private javax.swing.JMenuItem meltKelilingSegitiga;
    private javax.swing.JMenuItem meltLuasLingkaran;
    private javax.swing.JMenuItem meltLuasPersegiPanjang;
    private javax.swing.JMenuItem meltLuasSegitiga;
    private javax.swing.JMenu menHitung;
    private javax.swing.JMenu menProses;
    // End of variables declaration//GEN-END:variables
}
